/**
 * - Removes `http` if it's at the beginning (it is commonly with the default name generated by `makeHttpApi`)
 * - Converts non-alphanumeric characters into `_`
 * - Removes leading and trailing `_`
 * - Converts multiple `_` into single `_`
 * */
export const makeOpenApiSafeComponentNamePrefixDerivedFrom = (name: string) =>
  name
    .replace(/^http|[^a-z0-9_]/gi, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_');
